num_diverse_path: 16
chunk_size: 100
num_few_shot: 2
dataset: data/math/math_train.json
prompts: data/few_shots_prompts/math/few_shot_gpt4o.json
output_dir: data/math/generate/
use_vllm: true
resume_from_chunk: false

sampler:
  max_tokens: 1024
  temperature: 0.6
  top_p: 0.95
  top_k: -1

defaults:
  - _self_
  - models: Qwen2.5-1.5B-Instruct